#!/usr/bin/env bash

which node > /dev/null
if [ $? -ne 0  ]; then
    echo 
    echo "Warning: NodeJS not found in your PATH, stop"
    echo
    exit 1
fi

if [ ! -d ./list-generator/node_modules/underscore ]; then
    echo "install module dependencies..."
    cd list-generator; npm install; cd ..
fi

for f in $(ls list-generator/gen_*.js); do
  echo ""
  echo $f
  node $f
done

echo ""
echo "Generating Korean Codepoints"
node list-generator/_merge_k.js

echo ""
echo "Generating Korean+Japanese Codepoints"
node list-generator/_merge_kj.js
